// Shared part-category rules, derived from a part description.
//
// Lifted out of load-inventry.mjs so the CSV seeder (seed-from-csv.mjs) files
// parts into the same categories that loader does -- two copies of this list
// would drift the first time someone adds a keyword to one of them.

// ---- category from description -------------------------------------------
// Ordered; first hit wins. Falls back to 'accessories'.
const RULES = [
  [/\b(SEAT COVER|CAR COVER|STEERING WHEEL COVER|WHEEL COVER|MUD ?FLAP|MUD ?GUARD|FLOOR MAT|CAR MAT|AIR ?FRESHENER|FRAGRANCE|PHONE HOLDER|DASH ?CAM|\bTINT\b|\bANTENNA\b|CAR ALARM|REVERSE CAMERA|TOW ?HOOK|LICENSE FRAME|NUMBER PLATE|KEY ?CHAIN|AIR PUMP|JACK|WHEEL SPANNER|TYRE GAUGE|FIRE EXTINGUISHER|FIRST AID)\b/i, 'accessories'],
  [/\bSEAT ?BELT\b/i, 'body'],
  [/\bTIMING (BELT|CHAIN|KIT)\b/i, 'engine'],
  [/\b(FAN|DRIVE|SERPENTINE|POLY|V[- ]?)BELT\b|\bA\/?C BELT\b/i, 'engine'],
  [/\b(DISC PAD|BRAKE PAD|PAD SET|DISC ROTOR|BRAKE ROTOR|\bROTOR|BRAKE SHOE|BRAKE DISC|CALIPER|BRAKE MASTER|MASTER CYL|WHEEL CYL|BRAKE HOSE|BRAKE CABLE|HAND ?BRAKE|PARK(ING)? BRAKE|BRAKE BOOSTER|BOOSTER KIT|BRAKE WASHER|BRAKE DRUM|BRAKE LINING|ABS SENSOR|BRAKE PUMP)|\bBRAKE\b/i, 'brakes'],
  [/\b(WHEEL BEARING|HUB BEARING|WHEEL NUT|WHEEL STUD|WHEEL BOLT|LUG NUT|WHEEL LOCK|HUB ?CAP|\bRIM\b|\bWHEEL(?! COVER)|\bTYRE|\bTIRE|TUBELESS|INNER TUBE|KUMHO|BRIDGESTONE|MICHELIN|DUNLOP|GOODYEAR|FIRESTONE|YOKOHAMA|HANKOOK|\bTOYO\b|COMMERCIAL KC)\b/i, 'wheels'],
  [/\b(SHOCK|STRUT|STRU MOUNT|BALL JOINT|TIE ?ROD|RACK ?END|STEERING RACK|RACK (&|AND) PINION|DRAG LINK|CENTER LINK|CENTRE LINK|RELAY ROD|CONTROL ARM|LOWER ARM|UPPER ARM|A[- ]?ARM|WISHBONE|STABILI[SZ]ER|SWAY BAR|DROP LINK|LINK ROD|LINK STAY|\bBUSH\b|BUSHING|COIL SPRING|LEAF SPRING|\bSPRING|KING ?PIN|IDLER ARM|PITMAN ARM|RADIUS ROD|TRAILING ARM|SHACKLE|TORSION|CV ?BOOT|STEERING BOOT|SPRING SEAT|SHOCK MOUNT|SPINDLE)\b/i, 'suspension'],
  [/\b(OIL FILTER|AIR FILTER|FUEL FILTER|CABIN FILTER|TRANS(MISSION)? FILTER|\bFILTER|ENGINE OIL|MOTOR OIL|GEAR OIL|\bATF\b|\bCOOLANT|ANTI[- ]?FREEZE|BRAKE FLUID|POWER STEERING FLUID|P\/?S FLUID|\bGREASE|LUBRICANT|ADDITIVE|\bFLUSH|CLEANER|DEGREASER|SILICONE|EPOXY|URETHANE|SEALANT|\bRTV\b|THREAD ?LOCK|LOCTITE|WD[- ]?40|STOP LEAK|DIESEL TREATMENT|OCTANE|DOT ?[34]|GASKET MAKER|\bGLUE\b|GASKET CEMENT|PENETRAT|CARB CLEAN|CONTACT CLEAN)\b/i, 'fluids'],
  [/\b(BULB|SEALED BEAM|HEAD ?LAMP|HEAD ?LIGHT|TAIL ?LAMP|TAIL ?LIGHT|FOG ?LAMP|FOG ?LIGHT|SIDE ?MARKER|SIGNAL LAMP|CORNER LAMP|INDICATOR|\bLAMP|\bLIGHT|\bLED\b|\bHID\b|IGNITION (WIRE|COIL|CABLE|LEAD|MODULE)|SPARK PLUG|GLOW PLUG|PLUG (WIRE|LEAD|CABLE)|IGNITION WIRE|IGNITION COIL|COIL PACK|DISTRIBUTOR|ALTERNATOR|STARTER|BRUSH HOLDER|CARBON BRUSH|ALTERNATOR BRUSH|SOLENOID|\bRELAY|\bFUSE|\bSENSOR|\bSWITCH|\bHORN\b|BATTERY|TERMINAL|WIRE ?HARNESS|\bHARNESS|REGULATOR|RECTIFIER|FLASHER|WIPER MOTOR|WINDOW MOTOR|WASHER MOTOR|BLOWER MOTOR|FAN MOTOR|\bECU\b|\bECM\b|\bTCU\b|SPEEDOMETER|GAUGE CLUSTER)\b/i, 'electrical'],
  [/\b(MIRROR|\bDOOR|FENDER|BUMPER|GRIL+E|BONNET|\bHOOD\b|TRUNK|TAIL ?GATE|QUARTER PANEL|\bPANEL|MOUL?DING|MOLDING|DOOR HANDLE|\bHANDLE|WIND(SCREEN|SHIELD)|\bGLASS\b|\bHINGE|DOOR LOCK|\bLOCK\b|WEATHER ?STRIP|\bEMBLEM|\bBADGE|SPOILER|AIR ?DAM|\bSKIRT|SUN ?VISOR|RAIN ?VISOR|\bVISOR|SUN ?ROOF|WIPER (ARM|LINKAGE|BLADE)|SHOULDER PAD|HEADLINER|\bSEAT\b|\bDASH|\bCONSOLE|\bCARPET|BODY CLIP|FUEL (DOOR|LID)|LICENSE LAMP)\b/i, 'body'],
  [/\b(ENGINE|\bMOTOR\b|PISTON|\bRING\b|MAIN BEARING|CON[- ]?ROD|ROD BEARING|\bBEARING|\bCRANK|\bCAM\b|CAMSHAFT|\bVALVE|HEAD GASKET|\bGASKET|CYL(INDER)?|\bHEAD\b|MANIFOLD|TURBO|CARBURET+OR|CARB KIT|INJECTOR|\bPUMP\b|FUEL PUMP|LIFT PUMP|WATER PUMP|OIL PUMP|POWER ?STEERING PUMP|P\/?S PUMP|OIL SEAL|VALVE SEAL|\bSEAL\b|THERMOSTAT|RADIATOR|\bHOSE|\bMOUNT|CLUTCH|FLYWHEEL|PRESSURE PLATE|RELEASE BEARING|THROW ?OUT|CV ?JOINT|CV ?AXLE|DRIVE ?SHAFT|PROP(ELLER)? SHAFT|\bAXLE|TRANS(MISSION)?|GEAR ?BOX|\bCVT\b|DIFFERENTIAL|TIMING|TENSIONER|\bIDLER|\bPULLEY|\bCHAIN\b|OVERHAUL KIT|LINER KIT|PUSH ?ROD|ROCKER|LIFTER|TAPPET|EXHAUST|MUFFLER|CATALYTIC|FLEX PIPE|DOWN ?PIPE|\bEGR\b|\bPCV\b|\bBELT\b)\b/i, 'engine'],
];
function categorise(desc) {
  const s = ' ' + String(desc || '').toUpperCase() + ' ';
  // Also test a naively de-pluralised copy so "SHOCKS", "PADS", "MOUNTS",
  // "BEARINGS" etc. hit the same singular keyword.
  const sing = s.replace(/(\w{3})S\b/g, '$1');
  for (const [re, cat] of RULES) if (re.test(s) || re.test(sing)) return cat;
  return 'accessories';
}

export { RULES, categorise };
